### ISSUE TITLE
Terminal support

### ISSUE THREAD

**Issue by jacob-israel-turner** [trevordmiller/nova-iterm#20]
Apologies if this is not the correct place, I didn't see a central repo.

I have started using MacOS's default Terminal app, for performance reasons.  Apparently it also has better ligature support.

I miss using Nova!  Are there any plans in the future to support Nova for Terminal?  I'd be willing to help out where needed.

Thanks!

**Comment by trevordmiller** [comment]
@jacob-israel-turner Good question! I haven't looked into native mac terminal support as it hasn't been requested until now, but looking briefly [at some examples](https://github.com/lysyi3m/osx-terminal-themes/tree/master/schemes), it appears to be similar to the iterm setup. I'd recommend forking this, the `nova-iterm` project and adjusting the `src` string to build to a `build/nova.terminal` file, instead of `build/nova.itermcolors`. I'm not sure what would need to be changed but it seems a lot of the logic could be reused. If you make something that works, let me know and I can add it to the website :)

cc: @iammerrick

**Comment by trevordmiller** [comment]
@jacob-israel-turner Another option that would be quick, just for you, would be to manually adjust the colors in the terminal settings:
![image](https://cloud.githubusercontent.com/assets/5497885/24883204/304b3132-1e01-11e7-9055-978490230a38.png)
The colors list is available here:
https://github.com/trevordmiller/nova-colors/blob/master/src/index.js

**Comment by jacob-israel-turner** [comment]
It looks like we might lose some of the colors, due to Terminal.app not supporting true color.  I'll see what I can come up with!

Thanks!

**Comment by trevordmiller** [comment]
Sounds good. Closing this issue for now :) Thanks for using Nova.
